server:
  port: 8085

spring:
  application:
    name: mailing-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USER}
    password: ${EMAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8
    test-connection: false

  app:
    email:
      from: "Docease <${EMAIL_USER}>"
      enabled: true