spring:
  application:
    name: aiservice

  # === MongoDB ===
  data:
    mongodb:
      uri: mongodb://localhost:27017/docease

  # === MySQL ===
  datasource:
    firstaid:
      jdbc-url: jdbc:mysql://localhost:3306/aiservice_first_aid?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      firstaid:
        hibernate:
          ddl-auto: validate
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL8Dialect
        properties:
          hibernate:
            format_sql: true

server:
  port: 8088

# === Eureka Service Discovery
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761//eureka/

# --will add later
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true

gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}




